# --- !Ups

CREATE TABLE IF NOT EXISTS USER(
  ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  NAME VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS BLOG(
  ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  USER_ID INT NOT NULL,
  TITLE VARCHAR(200) NOT NULL,
  BODY VARCHAR(65535) NOT NULL,
  FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);

CREATE TABLE IF NOT EXISTS COMMENT(
  ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  USER_ID INT NOT NULL,
  BLOG_ID INT NOT NULL,
  BODY VARCHAR(65535) NOT NULL,
  FOREIGN KEY (USER_ID) REFERENCES USER(ID),
  FOREIGN KEY (BLOG_ID) REFERENCES BLOG(ID)
);

# --- !Downs

DROP TABLE IF EXISTS COMMENT;
DROP TABLE IF EXISTS BLOG;
DROP TABLE IF EXISTS USER;
